
# Site settings

url: http://maratonato.github.io
baseurl: ""
google-tracking-id: "UA-71312825-1"
force-https: False

syntax-highlight: True

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

web-app-mode: True

# Icons for Chrome Web App mode https://developer.chrome.com/multidevice/android/installtohomescreen
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

#############
# HTML Head #
#############

author: "ACM ICPC @ Tocantins"
lang: "en"
title: "@maratonato"
favicon: "/img/favicon.ico"
description: "Site da Maratona de Programação no Tocantins"
keywords: "maratona, programação, icpc, tocantins, brasil"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/icpc_logo.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: False
loop-count: 1 # Set False for infinite loop, or set any number for finite loop.
type-speed: 4
start-delay: 2000
delete-delay: 50000
lines: # You can add HTML Tags in the Text
  - text: "Este é o portal oficial da Maratona de Programação no Tocantins!"
  - text: "Keep coding"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "maratonato"

###############
# História #
###############

events:
  - image: "/img/timeline/uft.jpg"
    date: "[2009] UFT - Palmas, Tocantins"
    description: "[Maratona de Programação - Fase Regional]()"
  - image: "/img/timeline/uft.jpg"
    date: "[2010] UFT - Palmas, Tocantins"
    description: "[Maratona de Programação - Fase Regional]()"    
  - image: "/img/timeline/udesc.jpg"
    date: "[2010] UDESC - Joinville, Santa Catarina"
    description: "[Maratona de Programação - Final Nacional]()"
  - image: "/img/timeline/uft.jpg"
    date: "[2011] UFT - Palmas, Tocantins"
    description: "[Maratona de Programação - Fase Regional]()"
  - image: "/img/timeline/uft.jpg"
    date: "[2013] UFT - Palmas, Tocantins"
    description: "[Maratona de Programação - Fase Regional]()"  
  - image: "/img/timeline/uft.jpg"
    date: "[2015] UFT - Palmas, Tocantins"
    description: "[Maratona de Programação - Interna I]()"     
  - image: "/img/timeline/uft.jpg"
    date: "[2015] UFT - Palmas, Tocantins"
    description: "[Maratona de Programação - Fase Regional]()" 
  - image: "/img/timeline/ibta.png"
    date: "[2015] IBTA - São Paulo, São Paulo"
    description: "[Maratona de Programação - Fase Nacional]()"     

# First image of the Career timeline
timeline-img: "/img/timeline/default.png"

##################
# Contact layout #
##################

email: "maratona.to@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/maratonato"
  - title: "github"
    url: "https://github.com/maratonato"

############
# 404 page #
############

404-img: "/img/labtocat.png"

###############
# Highlighter #
###############

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Sobre: 'about'
  Blog: 'latest-post'
  História: 'timeline'
  Contato: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
